src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>jj_rb_National_Channel_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>National Channel Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/jj_rb_Estimated_Rebate_Accrual__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Estimated_Accrual__c</fullName>
        <label>Estimated Accrual</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rebate Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipName>Estimate_Rebate_Accruals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Estimated Rebate Accrual</label>
    <nameField>
        <displayFormat>ERA-{000}</displayFormat>
        <label>Estimated Rebate Accrual Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimated Rebate Accruals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Accrual__c.object
<CustomObject>
    <description>The information generated from the monthly execution of the rebate accruals is stored here.</description>
    <fields>
        <fullName>jj_rb_Customer_NCM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NCM associated with the customer.</description>
        <label>Customer National Channel Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rebate_Accruals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer for whom the rebate accrual record is created.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rebate Accruals</relationshipLabel>
        <relationshipName>Rebate_Accruals_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Accrual</label>
    <nameField>
        <displayFormat>RA-{000}</displayFormat>
        <label>Rebate Accrual Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Accruals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Accrual_Line_Item__c.object
<CustomObject>
    <description>Product line items present in the Rebate accrual form.</description>
    <fields>
        <fullName>jj_rb_Net_Rebate_Accrual_Amount__c</fullName>
        <label>Net Rebate Accrual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>jj_rb_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipLabel>Rebate Accrual Line Item</relationshipLabel>
        <relationshipName>Rebate_Accrual_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Accrual__c</fullName>
        <description>Master Rebate accrual for which these line items are created.</description>
        <label>Rebate Accrual</label>
        <referenceTo>jj_rb_Rebate_Accrual__c</referenceTo>
        <relationshipLabel>Rebate Accrual Line Item</relationshipLabel>
        <relationshipName>Rebate_Accrual_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Rebate Accrual Line Item</label>
    <nameField>
        <displayFormat>RALI-{000}</displayFormat>
        <label>Rebate Accrual Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Accrual Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Claim__c.object
<CustomObject>
    <description>This object will store the claim invoice submitted by the customer.</description>
    <fields>
        <fullName>jj_rb_Claim_Date__c</fullName>
        <formula>DATE(value(text(jj_rb_Year__c)) ,value(text(jj_rb_Month__c)) ,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Claim Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>jj_rb_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rebate Claims</relationshipLabel>
        <relationshipName>Rebate_Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Claim</label>
    <nameField>
        <displayFormat>CL-{0}</displayFormat>
        <label>Rebate Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Claim_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Hospital__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated hospital lookup field</description>
        <label>Hospital</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Net_Rebate__c</fullName>
        <formula>jj_rb_Quantity__c *  jj_rb_Rebate_Per_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Rebate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>jj_rb_Quantity__c</fullName>
        <description>Quantity of the product</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Claim__c</fullName>
        <label>Rebate Claim</label>
        <referenceTo>jj_rb_Rebate_Claim__c</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product for which rebate is being claimed.</description>
        <label>Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Rebate Claim Line Item</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Rebate Claim Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Claim Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Product__c.object
<CustomObject>
    <description>Information of the products sold to Retailers and homecare providers are stored here. A separate custom object created for products, as this application is a potential candidate for migration to iConnect and to minimize the impact on the standard Product object in iConnect.</description>
    <label>Rebate Product</label>
    <nameField>
        <label>Rebate Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rebate Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/jj_rb_rebateAccrualBaseClass.cls
/**
 *    @author  Sarabdeep Ahluwalia
 *    @date  1/04/2014
     @description  Base class for rebate accrual process
 
     Function: Base class for rebate accrual process
     Modification Log:
     ------------------------------------------------------------------------------------
     Developer              Date            Description
     ------------------------------------------------------------------------------------
     Sarabdeep Ahluwalia    1/04/2014      Original Version
 */
global abstract class jj_rb_rebateAccrualBaseClass
{
    // handles the accrual calculation for the new customer scenario
    protected void processAccrualForNewCustomer(Account customer, 
                                                    Map<Id, List<jj_rb_Estimated_Rebate_Accrual__c>> mapEstimatedAccruals,
                                                    Map<Id, jj_rb_Rebate_Accrual__c> mapRebateAccrual,
                                                    Map<Id, List<jj_rb_Rebate_Accrual_Line_Item__c>> mapRebateAccrualLI,id Recodtyp)
 {
    // for a new customer with no rebate claim, 
    // create a accrual record with the estimated accrual value
    // from the customer record.
    // get all the estimated accrual values for the customer
    List<jj_rb_Estimated_Rebate_Accrual__c> listEstimatedAccrual = mapEstimatedAccruals.get(customer.Id);
    
    if(listEstimatedAccrual != null && !listEstimatedAccrual.isEmpty()) 
    {
        // create the rebate accrual record first
        List<jj_rb_Rebate_Accrual_Line_Item__c> listRebateAccrualLI = new List<jj_rb_Rebate_Accrual_Line_Item__c>();
        jj_rb_Rebate_Accrual__c rebateAccrual = new jj_rb_Rebate_Accrual__c();
        rebateAccrual.RecordTypeID = Recodtyp;
        rebateAccrual.jj_rb_Customer__c = customer.Id;
        rebateAccrual.jj_rb_Month__c = Datetime.now().format('MM');
        rebateAccrual.jj_rb_Year__c = Datetime.now().format('YYYY');
        rebateAccrual.jj_rb_Customer_NCM__c = customer.jj_rb_National_Channel_Manager__c;
        mapRebateAccrual.put(customer.Id, rebateAccrual);
        
        for(jj_rb_Estimated_Rebate_Accrual__c estimatedAccrual : listEstimatedAccrual)
        {
            jj_rb_Rebate_Accrual_Line_Item__c rebateAccrualLI = new jj_rb_Rebate_Accrual_Line_Item__c();
            rebateAccrualLI.jj_rb_Rebate_Accrual__c = rebateAccrual.Id;     
            rebateAccrualLI.jj_rb_Product__c = estimatedAccrual.jj_rb_Rebate_Product__c;
            rebateAccrualLI.jj_rb_Net_Rebate_Accrual_Amount__c = estimatedAccrual.jj_rb_Estimated_Accrual__c;
            rebateAccrualLI.jj_rb_Volume__c = 0;
            
            system.debug('rebateAccrualLI >>>>>>' + rebateAccrualLI);
            listRebateAccrualLI.add(rebateAccrualLI);   
        }
        mapRebateAccrualLI.put(customer.Id, listRebateAccrualLI);
    }   
 }  
 
 global void calcAccrualForExistingCustomer(Account customer, List<jj_rb_Rebate_Claim__c> listClaims, 
                                                    Map<Id, jj_rb_Rebate_Accrual__c> mapRebateAccrual,
                                                    Map<Id, List<jj_rb_Rebate_Accrual_Line_Item__c>> mapRebateAccrualLI, id Recodtyp)
 {
    // take the average of quantity and net rebate
    Map<Id, accrualCalc> mapAccrualCal = new map<Id, accrualCalc>();
    
    // find the minimum difference in the claim period and accrual execution month
    Integer monthDiff = 99;
    for(jj_rb_Rebate_Claim__c claim : listClaims)
    {       
        Integer monthInBetween = claim.jj_rb_Claim_Date__c.monthsBetween(Date.today());
        system.debug('claim date >>>>>' + claim.jj_rb_Claim_Date__c + ' monthInBetween>>>' + monthInBetween);
        if (monthInBetween < monthDiff)
        {
            // reducing one month so that rollup does not happen for the current month.
            monthDiff = monthInBetween;
        }       
    }
    
    if(monthDiff == 99)
        monthDiff = 1; 
        
    system.debug('monthDiff>>>' + monthDiff);   
    
    // calculate 
    for(jj_rb_Rebate_Claim__c claim : listClaims)
    {
        List<jj_rb_Rebate_Claim_Line_Item__c> claimLineItems = claim.Rebate_Claim_Line_Items__r;
        Decimal qty = 0;
        Decimal netRebate = 0;
        for(jj_rb_Rebate_Claim_Line_Item__c claimLI : claimLineItems)
        {
            String productId = claimLI.jj_rb_Rebate_Product__c;
            
            // Calculate qty
            if(mapAccrualCal.containsKey(productId))
            {
                accrualCalc calc = mapAccrualCal.get(productId);
                calc.itemCount += 1;
                calc.Qty += claimLI.jj_rb_Quantity__c;
                calc.netRebate += claimLI.jj_rb_Net_Rebate__c;
                mapAccrualCal.put(productId, calc);                         
            } else {
                accrualCalc calc = new accrualCalc();
                calc.itemCount = 1;
                calc.Qty = claimLI.jj_rb_Quantity__c;
                calc.netRebate = claimLI.jj_rb_Net_Rebate__c;
                mapAccrualCal.put(productId, calc);         
            }           
        }
    }
    
    system.debug('mapAccrualCal>>>>' + mapAccrualCal);
    
    // create rebate Accrual record
    
    jj_rb_Rebate_Accrual__c rebateAccrual = new jj_rb_Rebate_Accrual__c(); 
    rebateAccrual.jj_rb_Customer__c = customer.Id;
    rebateAccrual.RecordTypeId = Recodtyp; 
    rebateAccrual.jj_rb_Month__c = Datetime.now().format('MM');
    rebateAccrual.jj_rb_Year__c = Datetime.now().format('YYYY');
    rebateAccrual.jj_rb_Customer_NCM__c = customer.jj_rb_National_Channel_Manager__c;
    mapRebateAccrual.put(customer.Id, rebateAccrual);
    
    // Create rebate accrual line item records
    List<jj_rb_Rebate_Accrual_Line_Item__c> accrualLineItems = new List<jj_rb_Rebate_Accrual_Line_Item__c>();
    for(String productId : mapAccrualCal.KeySet())
    {
        accrualCalc calc = mapAccrualCal.get(productId);
        
        jj_rb_Rebate_Accrual_Line_Item__c rebateAccrualLI = new jj_rb_Rebate_Accrual_Line_Item__c();
        rebateAccrualLI.jj_rb_Volume__c = Math.round(calc.getAvgQty()) * monthDiff;
        rebateAccrualLI.jj_rb_Net_Rebate_Accrual_Amount__c = calc.getAvgNetRebate() * monthDiff;  
        rebateAccrualLI.jj_rb_Product__c = productId;
        accrualLineItems.add(rebateAccrualLI); 
    }
    mapRebateAccrualLI.put(customer.Id, accrualLineItems);
                                                        
 }
 protected void createAccruals(Map<Id, jj_rb_Rebate_Accrual__c> mapRebateAccrual,
                                                    Map<Id, List<jj_rb_Rebate_Accrual_Line_Item__c>> mapRebateAccrualLI)
 {
     list<jj_rb_Rebate_Accrual__c> listupdateAcc = new list<jj_rb_Rebate_Accrual__c>();
     List<jj_rb_Rebate_Accrual_Line_Item__c> listRebateAccrualLI = new List<jj_rb_Rebate_Accrual_Line_Item__c>();
     system.debug('mapRebateAccrual>>>>' + mapRebateAccrual); 
     system.debug('mapRebateAccrualLI>>>>' + mapRebateAccrualLI);  
     if(!mapRebateAccrual.values().isEmpty())
     {
         /*
         for(jj_rb_Rebate_Accrual__c RebateAcc : mapRebateAccrual.values())
         { 
             RebateAcc.RecordTypeId = Recodtyp;
             listupdateAcc .add(RebateAcc);
         }
         */
        insert mapRebateAccrual.values();       
     } 
     if(!mapRebateAccrualLI.keySet().isEmpty()) 
     {
        for(String custId : mapRebateAccrualLI.keySet()) 
         { 
              jj_rb_Rebate_Accrual__c rebateAccrual = mapRebateAccrual.get(custId);
              if(rebateAccrual!=null)
              {
                List<jj_rb_Rebate_Accrual_Line_Item__c> listRALI = mapRebateAccrualLI.get(custId);
                if(listRALI != null && !listRALI.isEmpty())
                {
                    for(jj_rb_Rebate_Accrual_Line_Item__c rali : listRALI)
                    {
                        rali.jj_rb_Rebate_Accrual__c = rebateAccrual.id;
                        listRebateAccrualLI.add(rali);
                    }
                    
                }
              }   
         }
        insert  listRebateAccrualLI;
     }
     
     // create the approval process for Rebate accrual
     for(jj_rb_Rebate_Accrual__c rebateaccrual : mapRebateAccrual.values())
     {
       Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
       system.debug('approval rebate accrual>>>' + rebateaccrual);
       req1.setObjectId(rebateaccrual.id);  
       Approval.ProcessResult result = Approval.process(req1);
      }
 }                                                   
 class accrualCalc {
  String productId;
  Integer itemCount;
  Decimal Qty;
  Decimal netRebate;
  
  public Decimal getAvgQty()
  {
    return Qty/itemCount;
  }
  public Decimal getAvgNetRebate()
  {
    return netRebate/itemCount;
  }
} 
}