src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>jj_rb_NHS_Trust__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>NHS Trust</label>
        <referenceTo>jj_rb_NHS_Trust__c</referenceTo>
        <relationshipLabel>Hospitals</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/jj_rb_Master_Data_RecordTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting lists all the record types for master data request object</description>
    <label>Master Data Record Types</label>
</CustomObject>

src/objects/jj_rb_NHS_Trust__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Region</label>
        <referenceTo>jj_rb_Region__c</referenceTo>
        <relationshipLabel>NHS Trusts</relationshipLabel>
        <relationshipName>NHS_Trusts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>NHS Trust</label>
    <nameField>
        <label>NHS Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NHS Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Claim__c.object
<CustomObject>
    <description>This object will store the claim invoice submitted by the customer.</description>
    <fields>
        <fullName>jj_rb_Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Claim</label>
    <nameField>
        <displayFormat>CL-{0}</displayFormat>
        <label>Rebate Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Claim_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Rebate_Claim__c</fullName>
        <label>Rebate Claim</label>
        <referenceTo>jj_rb_Rebate_Claim__c</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product for which rebate is being claimed.</description>
        <label>Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Rebate Claim Line Item</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Rebate Claim Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Claim Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Contract__c.object
<CustomObject>
    <description>This object stores the contract information created for a customer.</description>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Contract</label>
    <nameField>
        <displayFormat>RC-{0}</displayFormat>
        <label>Rebate Contract No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Contract_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Rebate_Contract__c</fullName>
        <label>Rebate Contract</label>
        <referenceTo>jj_rb_Rebate_Contract__c</referenceTo>
        <relationshipLabel>Rebate Contract Line Items</relationshipLabel>
        <relationshipName>Rebate_Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>jj_rb_Region__c</referenceTo>
        <relationshipLabel>Rebate Contract Line Items</relationshipLabel>
        <relationshipName>Rebate_Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Contract Line Item</label>
    <nameField>
        <displayFormat>RCLI-{0}</displayFormat>
        <label>Rebate Contract Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Product__c.object
<CustomObject>
    <description>Information of the products sold to Retailers and homecare providers are stored here. A separate custom object created for products, as this application is a potential candidate for migration to iConnect and to minimize the impact on the standard Product object in iConnect.</description>
    <label>Rebate Product</label>
    <nameField>
        <label>Rebate Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rebate Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/jj_rb_Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/jj_rb_Tolerance__c.object
<CustomObject>
    <description>This Object stores Tolerance Details</description>
    <label>Tolerance</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Tolerance No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tolerance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/jj_rb_Test_RebateClaims.cls
/**
 *    @author  Sarabdeep Ahluwalia
 *    @date  5/05/2014
      @description  Test class for the Rebate Claims
     
     Modification Log:
     ------------------------------------------------------------------------------------
     Developer              Date            Description
     ------------------------------------------------------------------------------------     
     Sarabdeep Ahluwalia    5/05/2014      	Original
 */
@isTest
private class jj_rb_Test_RebateClaims {
	
	// test creation of retailer claims
	static testmethod void createRetailerClaims()
	{
		User rebateUser = jj_rb_Test_BaseClass.setupUser();       
        
        Test.startTest();
        
        system.runAs(rebateUser) { 
        	jj_rb_Test_BaseClass.setupRebateAnalystUser(rebateUser);
        	
        	// setup custom settings
        	List<jj_rb_Master_Data_RecordTypes__c> listCS =  jj_rb_Test_BaseClass.createRecordTypeCustomSetting();
        	insert listCS; 
        	
        	// setup a retailer account
        	Account retailer = jj_rb_Test_BaseClass.setupRetailerCustomer(rebateUser);
        	insert retailer;
        	
        	// setup rebate product
        	jj_rb_Rebate_Product__c rebateProduct = jj_rb_Test_BaseClass.setupRebateProduct();
        	insert rebateProduct;
        	
        	// setup retailer contract
        	jj_rb_Rebate_Contract__c contract = jj_rb_Test_BaseClass.setupRetailerContract(retailer, rebateUser);
        	insert contract;
        	
        	// setup cpntract line items
        	jj_rb_Rebate_Contract_Line_Item__c conLI = jj_rb_Test_BaseClass.setupRetailerContractLineItem(contract, rebateProduct);
        	insert conLI;
        	
        	// update the contract status
        	contract.jj_rb_status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
        	update contract;
        	
        	// create a retailer claim
        	jj_rb_Rebate_Claim__c retailerClaim1 = jj_rb_Test_BaseClass.setupRetailerClaim(retailer);
        	retailerClaim1.jj_rb_month__c = '03';
        	retailerClaim1.jj_rb_Year__c = '2014';
        	insert retailerClaim1;
        	
        	// create retailer line items
        	jj_rb_Rebate_Claim_Line_Item__c cli1 = jj_rb_Test_BaseClass.setupRetailerClaimLineItems(retailerClaim1, rebateProduct);
        	insert cli1;
        	
        	// create second claim
        	jj_rb_Rebate_Claim__c retailerClaim2 = jj_rb_Test_BaseClass.setupRetailerClaim(retailer);
        	retailerClaim2.jj_rb_month__c = '04';
        	retailerClaim2.jj_rb_Year__c = '2014';
        	insert retailerClaim2;
        	
        	// create retailer line items
        	jj_rb_Rebate_Claim_Line_Item__c cli2 = jj_rb_Test_BaseClass.setupRetailerClaimLineItems(retailerClaim2, rebateProduct);
        	insert cli2;
        	
        	// approve the claim
        	retailerClaim1.jj_rb_status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
        	retailerClaim2.jj_rb_status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
        	update new List<jj_rb_Rebate_Claim__c>{retailerClaim1,retailerClaim2}; 
        	
        }
        test.stopTest();
	}
	
	static testmethod void createHCPClaim()
	{
		User rebateUser = jj_rb_Test_BaseClass.setupUser();       
        
        Test.startTest();
        
        system.runAs(rebateUser) { 
        	jj_rb_Test_BaseClass.setupRebateAnalystUser(rebateUser);
        	
        	// setup custom settings
        	List<jj_rb_Master_Data_RecordTypes__c> listCS =  jj_rb_Test_BaseClass.createRecordTypeCustomSetting();
        	insert listCS; 
        	
        	// setup a retailer account
        	Account customer = jj_rb_Test_BaseClass.setupHomecareCustomer(rebateUser);
        	insert customer;
        	
        	// setup rebate product
        	jj_rb_Rebate_Product__c rebateProduct = jj_rb_Test_BaseClass.setupRebateProduct();
        	insert rebateProduct;
        	
        	// setup region
        	jj_rb_Region__c region = jj_rb_Test_BaseClass.setupRegion();
        	insert region;
        	
        	// set NHS Trust
        	jj_rb_NHS_Trust__c trust = jj_rb_Test_BaseClass.setupTrust(region);
        	insert trust;
        	
        	// create hospital
        	Account hospital = jj_rb_Test_BaseClass.setupHospital(trust, rebateUser);
        	insert hospital;
        	
        	// setup homecare contract
        	jj_rb_Rebate_Contract__c hcpContract = jj_rb_Test_BaseClass.setupHomecareContract(rebateProduct, rebateUser);
        	insert hcpContract;
        	        	
        	// setup contract line items
        	jj_rb_Rebate_Contract_Line_Item__c cli = jj_rb_Test_BaseClass.setupHomecareContractLineItem(hcpContract, region);
        	insert cli;        	
        	
        	// approve the contract
        	hcpContract.jj_rb_status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
        	update hcpContract;
        	
        	// approve the contract
        	hcpContract.jj_rb_status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
        	update hcpContract;       	
        	
        	// create a hcp claim
        	jj_rb_Rebate_Claim__c hcpClaim = jj_rb_Test_BaseClass.setupHCPClaim(customer);
        	hcpClaim.jj_rb_Month__c = '02';
        	hcpClaim.jj_rb_Year__c = '2014';
        	insert hcpClaim;
        	
        	
        	// create claim line items
        	jj_rb_Rebate_Claim_Line_Item__c claimCLI = jj_rb_Test_BaseClass.setupHCPClaimLineItems(hcpClaim, rebateProduct, hospital);
        	insert claimCLI;        	
        	
        	// approve the claim
        	hcpClaim.jj_rb_Status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
        	update hcpClaim;
        	
        }
        test.stopTest();
	}

	
	static testmethod void testAvgQuantityCalculation()
	{
		User rebateUser = jj_rb_Test_BaseClass.setupUser();       
        
        Test.startTest();
        
        system.runAs(rebateUser) { 
        	jj_rb_Test_BaseClass.setupRebateAnalystUser(rebateUser);
        	jj_rb_Test_BaseClass.setupRebateNCMUser(rebateUser); 
        	
        	// setup custom settings
        	List<jj_rb_Master_Data_RecordTypes__c> listCS =  jj_rb_Test_BaseClass.createRecordTypeCustomSetting();
        	insert listCS; 
        	
        	// setup hcp customer 
        	Account hcp = jj_rb_Test_BaseClass.setupHomecareCustomer(rebateUser);
        	insert hcp;
        	
        	// setup rebate product
        	jj_rb_Rebate_Product__c rebateProduct = jj_rb_Test_BaseClass.setupRebateProduct();
        	insert rebateProduct;
        	
        	// setup region
        	jj_rb_Region__c region = jj_rb_Test_BaseClass.setupRegion();
        	insert region;
        	
        	// set NHS Trust
        	jj_rb_NHS_Trust__c trust = jj_rb_Test_BaseClass.setupTrust(region);
        	insert trust;
        	
        	// create hospital
        	Account hospital = jj_rb_Test_BaseClass.setupHospital(trust, rebateUser);
        	insert hospital;
        	
        	// setup homecare contract
        	jj_rb_Rebate_Contract__c hcpContract = jj_rb_Test_BaseClass.setupHomecareContract(rebateProduct, rebateUser);
        	insert hcpContract;
        	
        	// setup contract line items
        	jj_rb_Rebate_Contract_Line_Item__c cli = jj_rb_Test_BaseClass.setupHomecareContractLineItem(hcpContract, region);
        	insert cli;        	
        	
        	// approve the contract
        	hcpContract.jj_rb_status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
        	update hcpContract;
        	
        	// approve the contract line item also
        	cli.jj_rb_Status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
        	update cli;
        	
        	// create a hcp claim
        	jj_rb_Rebate_Claim__c claim = jj_rb_Test_BaseClass.setupHCPClaim(hcp);        	
        	insert claim;
        	
        	// create line items
        	jj_rb_Rebate_Claim_Line_Item__c claimCLI = jj_rb_Test_BaseClass.setupHCPClaimLineItems(claim, rebateProduct, hospital);
        	insert claimCLI;
        	
        	// approve the claim
        	claim.jj_rb_status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
        	update claim;
        	
        	// setup tolerance
        	jj_rb_Tolerance__c tol = jj_rb_Test_BaseClass.setupTolerance(hcp, rebateProduct);
        	insert tol;        	       	
        }
        
        
        	// check avg qty
        	jj_rb_avgQuantityCalc batch = new jj_rb_avgQuantityCalc();
        	batch.homecareclaim_recType = jj_rb_Test_BaseClass.getRecordTypeId('Homecare Claim', 'jj_rb_Rebate_Claim__c');
        	batch.status_approved = jj_rb_Test_BaseClass.STATUS_APPROVED;
        	Database.executeBatch(batch);
        	
        	// run the scheduler too        	
        	//jj_rb_avgQuantityCalcScheduler sch = new jj_rb_avgQuantityCalcScheduler();
        	//sch.execute(null);
        	
        test.stopTest();
        	
	}
	
	static testMethod void testNewClaimLineItemOverride()
	{
	   // setup running user
        User rebateUser = jj_rb_Test_BaseClass.setupUser();       
        
        Test.startTest();
        
        system.runAs(rebateUser) {   
        	// setup custom settings
        	List<jj_rb_Master_Data_RecordTypes__c> listCS =  jj_rb_Test_BaseClass.createRecordTypeCustomSetting();
        	insert listCS; 
        	
        	// setup a retailer account
        	Account retailer = jj_rb_Test_BaseClass.setupRetailerCustomer(rebateUser);
        	insert retailer;
        	
        	// setup rebate product
        	jj_rb_Rebate_Product__c rebateProduct = jj_rb_Test_BaseClass.setupRebateProduct();
        	insert rebateProduct;
        	
        	// create a retailer claim
        	jj_rb_Rebate_Claim__c retailerClaim = jj_rb_Test_BaseClass.setupRetailerClaim(retailer);
        	insert retailerClaim;
        	
        	// create retailer line items
        	jj_rb_Rebate_Claim_Line_Item__c cli = jj_rb_Test_BaseClass.setupRetailerClaimLineItems(retailerClaim, rebateProduct);
        	insert cli;
        	
        	Pagereference pageRef = Page.jj_rb_Claim_Line_Item_NewOverridepage;
        	Test.setCurrentPage(pageRef);
        	ApexPages.currentPage().getParameters().put('XXX_lkid',retailerClaim.Id);
        	
        	jj_rb_NewClaimLineItemOverride controller = new jj_rb_NewClaimLineItemOverride(new Apexpages.standardController(cli));
        	system.assertNotEquals(null, controller.url());
        }	
                
        Test.stopTest();   		
	}
	

}