src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>jj_rb_National_Channel_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>National Channel Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/jj_rb_Rebate_Contract__c.object
<CustomObject>
    <description>This object stores the contract information created for a customer.</description>
    <fields>
        <fullName>jj_rb_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rebate Contracts</relationshipLabel>
        <relationshipName>Rebate_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_National_Channel_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>National Channel Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rebate_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Contract</label>
    <nameField>
        <displayFormat>RC-{0}</displayFormat>
        <label>Rebate Contract No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Contract_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Rebate_Contract__c</fullName>
        <label>Rebate Contract</label>
        <referenceTo>jj_rb_Rebate_Contract__c</referenceTo>
        <relationshipLabel>Rebate Contract Line Items</relationshipLabel>
        <relationshipName>Rebate_Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Contract Line Item</label>
    <nameField>
        <displayFormat>RCLI-{0}</displayFormat>
        <label>Rebate Contract Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/jj_rb_EditcontractLineItemOverrideclass.cls
public with sharing class jj_rb_EditcontractLineItemOverrideclass {
    public ApexPages.StandardController controller;
    public jj_rb_Rebate_Contract_Line_Item__c conlineitems;
    public string recordtype{set;get;}
    public String retURL {get; set;}
    public string status{set;get;}
    public string customer{set;get;}
    public string contract{set;get;}
   
    
      
    
    // Record Types of contract an lineitems
    String retailerclosed_recordType=jj_rb_Rebate_utils.getRecordTypeId('Retailer_Closed_Contract');
    String HomecareClosed_recordType=jj_rb_Rebate_utils.getRecordTypeId('Homecare_Closed_Contract');
    String contractlineClosed_recordType=jj_rb_Rebate_utils.getRecordTypeId('Retailer_Closed_Contract_Line_Item');
    String HCPlineitemClosed_recordType=jj_rb_Rebate_utils.getRecordTypeId('Homecare_Closed_Contract_Lineitem');
    String RetailerConLineitem_RT=jj_rb_Rebate_utils.getRecordTypeId('Contract_LineItem_Retailer');
    String HCPConLineItem_RT=jj_rb_Rebate_utils.getRecordTypeId('Homecare_Contract_Line_Item');
    String Status_closed=jj_rb_Rebate_utils.getRebateLineItemStatus('Closed');
    String Status_Expired=jj_rb_Rebate_utils.getRebateLineItemStatus('Expired');    
   
    public jj_rb_EditcontractLineItemOverrideclass(ApexPages.StandardController controller) {
        this.controller=controller;
        status=ApexPages.currentPage().getParameters().get('conlineitems.jj_rb_Status__c');
        recordtype=ApexPages.currentPage().getParameters().get('conlineitems.RecordType.name');
        contract=ApexPages.currentPage().getParameters().get('conlineitems.jj_rb_Rebate_Contract__c');
        customer=ApexPages.currentPage().getParameters().get('conlineitems.jj_rb_Rebate_Contract__r.jj_rb_customer__c');
        retURL = ApexPages.currentPage().getParameters().get('retURL');        
    }
    
    public Pagereference edit()
    {
        PageReference returnURL;
        conlineitems=(jj_rb_Rebate_Contract_Line_Item__c)controller.getRecord();
        //get the Rebate contract line items
        conlineitems=[select jj_rb_Status__c,jj_rb_Rebate_Contract__r.jj_rb_National_Channel_Manager__r.Name,
                            RecordTypeId,RecordType.name,jj_rb_Rebate_Contract__r.name,jj_rb_Rebate_Contract__r.jj_rb_customer__r.name,
                            jj_rb_Rebate_Contract__r.jj_rb_Status__c from jj_rb_Rebate_Contract_Line_Item__c
                            where id=:conlineitems.id];
        
        System.debug('@@@contractlineitems@@@@'+conlineitems);
        System.debug('@@@contractlineitems@@@@'+conlineitems.jj_rb_Status__c);
        System.debug('@@@contractlineitems@@@@'+conlineitems.RecordTypeID);
        
        if((conlineitems.jj_rb_Status__c==Status_Expired ||conlineitems.jj_rb_Status__c==Status_closed) 
                && (conlineitems.RecordTypeID==contractlineClosed_recordType || conlineitems.RecordTypeID==HCPlineitemClosed_recordType 
                    || conlineitems.RecordTypeID==HCPConLineItem_RT ||conlineitems.RecordTypeID==RetailerConLineitem_RT))
        {
           returnURL=new PageReference('/apex/jj_rb_contractLineItemEditOverride');
          
        }
        else 
        {
           
            returnURL=new PageReference('/'+conlineitems.id+'/e?nooverride=1');
           
        }
        returnURL.getParameters().put('retURL',retURL ); 
        returnURL.getParameters().put('recordtype',conlineitems.RecordType.name);
        returnURL.getParameters().put('Status',conlineitems.jj_rb_Status__c);
        returnURL.getParameters().put('contract',conlineitems.jj_rb_Rebate_Contract__r.name);
        returnURL.getParameters().put('customer',conlineitems.jj_rb_Rebate_Contract__r.jj_rb_customer__r.name);
        returnURL.getParameters().put('NCM',conlineitems.jj_rb_Rebate_Contract__r.jj_rb_National_Channel_Manager__r.Name);
        returnURL.getParameters().put('nooverride', '1');
        
        returnURL.setRedirect(true);
        

    return returnURL;
    }
    
   
    
}