src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>jj_rb_IMS_Customer_Id__c</fullName>
        <externalId>true</externalId>
        <label>IMS Customer Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>jj_rb_National_Channel_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>National Channel Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_SAP_Customer_Number__c</fullName>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/jj_rb_Estimated_Rebate_Accrual__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Rebate_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rebate Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipName>Estimate_Rebate_Accruals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Estimated Rebate Accrual</label>
    <nameField>
        <displayFormat>ERA-{000}</displayFormat>
        <label>Estimated Rebate Accrual Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimated Rebate Accruals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Accrual__c.object
<CustomObject>
    <description>The information generated from the monthly execution of the rebate accruals is stored here.</description>
    <fields>
        <fullName>jj_rb_Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Accrual</label>
    <nameField>
        <displayFormat>RA-{000}</displayFormat>
        <label>Rebate Accrual Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Accruals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Accrual_Line_Item__c.object
<CustomObject>
    <description>Product line items present in the Rebate accrual form.</description>
    <fields>
        <fullName>jj_rb_Rebate_Accrual__c</fullName>
        <description>Master Rebate accrual for which these line items are created.</description>
        <label>Rebate Accrual</label>
        <referenceTo>jj_rb_Rebate_Accrual__c</referenceTo>
        <relationshipLabel>Rebate Accrual Line Item</relationshipLabel>
        <relationshipName>Rebate_Accrual_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rebate Accrual Line Item</label>
    <nameField>
        <displayFormat>RALI-{000}</displayFormat>
        <label>Rebate Accrual Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Accrual Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Claim__c.object
<CustomObject>
    <description>This object will store the claim invoice submitted by the customer.</description>
    <fields>
        <fullName>jj_rb_Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Claim</label>
    <nameField>
        <displayFormat>CL-{0}</displayFormat>
        <label>Rebate Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Claim_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Rebate_Claim__c</fullName>
        <label>Rebate Claim</label>
        <referenceTo>jj_rb_Rebate_Claim__c</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product for which rebate is being claimed.</description>
        <label>Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Rebate Claim Line Item</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Rebate Claim Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Claim Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Contract__c.object
<CustomObject>
    <description>This object stores the contract information created for a customer.</description>
    <fields>
        <fullName>jj_rb_National_Channel_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>National Channel Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rebate_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Contract</label>
    <nameField>
        <displayFormat>RC-{0}</displayFormat>
        <label>Rebate Contract No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Contract_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Rebate_Contract__c</fullName>
        <label>Rebate Contract</label>
        <referenceTo>jj_rb_Rebate_Contract__c</referenceTo>
        <relationshipLabel>Rebate Contract Line Items</relationshipLabel>
        <relationshipName>Rebate_Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>jj_rb_Region__c</referenceTo>
        <relationshipLabel>Rebate Contract Line Items</relationshipLabel>
        <relationshipName>Rebate_Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Contract Line Item</label>
    <nameField>
        <displayFormat>RCLI-{0}</displayFormat>
        <label>Rebate Contract Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/jj_rb_Test_Rebate_Accruals.cls
/**
 *    @author  Sarabdeep Ahluwalia
 *    @date  5/05/2014
      @description  Test class for the Rebate accruals
     
     Modification Log:
     ------------------------------------------------------------------------------------
     Developer              Date            Description
     ------------------------------------------------------------------------------------     
     Sarabdeep Ahluwalia    5/05/2014       Original
 */
@isTest
private class jj_rb_Test_Rebate_Accruals {
    static testMethod void testAccrualActionButtons()
    {       
        User rebateUser = jj_rb_Test_BaseClass.setupUser();       
        
        Test.startTest();
        
        system.runAs(rebateUser) { 
            jj_rb_Test_BaseClass.setupRebateAnalystUser(rebateUser);
            jj_rb_Test_BaseClass.setupRebateNCMUser(rebateUser);
            
            // fill the customset for recordtypes
            List<jj_rb_Master_Data_RecordTypes__c> listRecType = jj_rb_Test_BaseClass.createRecordTypeCustomSetting();
            insert listRecType;
            
            // create a product
            jj_rb_Rebate_Product__c product = jj_rb_Test_BaseClass.setupRebateProduct();
            insert product;
            
            // create a retailer first
            Account retailer = jj_rb_Test_BaseClass.setupRetailerCustomer(rebateUser);
            insert retailer;
            
            // create rebate accrual record
            jj_rb_Rebate_Accrual__c ra = jj_rb_Test_BaseClass.setupRetailerAccrual(retailer);
            ra.jj_rb_status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
            ra.jj_rb_Month__c = Datetime.now().format('MM');
            ra.jj_rb_Year__C = Datetime.now().format('YYYY');
            insert ra;
            
            // create line items
            jj_rb_Rebate_Accrual_Line_Item__c raCLI = jj_rb_Test_BaseClass.setupAccrualLineItem(ra, product);
            insert raCLI;
            
            jj_rb_Accrual_Actions.createBatchReport();
            
        }   
    }
    
    static testMethod void testRetailerAccrualForExistingCustomer()
    {
        User rebateUser = jj_rb_Test_BaseClass.setupUser();       
        
        Test.startTest();
        
        system.runAs(rebateUser) { 
            jj_rb_Test_BaseClass.setupRebateAnalystUser(rebateUser);
            jj_rb_Test_BaseClass.setupRebateNCMUser(rebateUser);
            
            // fill the customset for recordtypes
            List<jj_rb_Master_Data_RecordTypes__c> listCS = jj_rb_Test_BaseClass.createRecordTypeCustomSetting();                                                                               
            insert listCS;
            
            // create a product
            jj_rb_Rebate_Product__c product = jj_rb_Test_BaseClass.setupRebateProduct();
            insert product;
            
            // create a retailer first
            Account retailer = jj_rb_Test_BaseClass.setupRetailerCustomer(rebateUser);
            insert retailer;
            
            // setup era
            jj_rb_Estimated_Rebate_Accrual__c era = jj_rb_Test_BaseClass.setupERA(retailer, product); 
            insert era;
            
            // create a retailer contract
            jj_rb_Rebate_Contract__c contract = jj_rb_Test_BaseClass.setupRetailerContract(retailer, rebateUser);           
            insert contract;
            
            // create contract line items
            jj_rb_Rebate_Contract_Line_Item__c cli = jj_rb_Test_BaseClass.setupRetailerContractLineItem(contract, product);
            insert cli;
            
            // approve the contract
            contract.jj_rb_Status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
            update contract;
            
            // create a retailer claim
            jj_rb_Rebate_Claim__c claim = jj_rb_Test_BaseClass.setupRetailerClaim(retailer);
            insert claim;
            
            // create claim line item
            jj_rb_Rebate_Claim_Line_Item__c claimLI = jj_rb_Test_BaseClass.setupRetailerClaimLineItems(claim, product);
            insert claimLI;
            
            // approve the claim
            claim.jj_rb_Status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
            update claim;           
            
            // run the retailer accrual batch process
            //jj_rb_RetailerAccrualCalc batch = new jj_rb_RetailerAccrualCalc();
            //batch.retailer_contract = jj_rb_Test_BaseClass.getRecordTypeId('Retailer Contract', 'jj_rb_Rebate_Contract__c');
            //database.executeBatch(batch);
            jj_rb_RebateAccrualCalcScheduler sched = new jj_rb_RebateAccrualCalcScheduler();
            sched.execute(null);        
            
        }
        
     
        
        
        Test.stopTest();    
    }
    
    static testMethod void testRetailerAccrualForNewCustomer()
    {
        User rebateUser = jj_rb_Test_BaseClass.setupUser();       
        
        Test.startTest();
        
        system.runAs(rebateUser) { 
            jj_rb_Test_BaseClass.setupRebateAnalystUser(rebateUser);
            jj_rb_Test_BaseClass.setupRebateNCMUser(rebateUser);
            
            // fill the customset for recordtypes
            List<jj_rb_Master_Data_RecordTypes__c> listRecType = jj_rb_Test_BaseClass.createRecordTypeCustomSetting();
            insert listRecType;
            
            // create a product
            jj_rb_Rebate_Product__c product = jj_rb_Test_BaseClass.setupRebateProduct();
            insert product;
            
            // create a retailer first
            Account retailer = jj_rb_Test_BaseClass.setupRetailerCustomer(rebateUser);
            insert retailer;
            
            // setup era
            jj_rb_Estimated_Rebate_Accrual__c era = jj_rb_Test_BaseClass.setupERA(retailer, product); 
            insert era;
            
            // create a retailer contract
            jj_rb_Rebate_Contract__c contract = jj_rb_Test_BaseClass.setupRetailerContract(retailer, rebateUser);           
            insert contract;
            
            // create contract line items
            jj_rb_Rebate_Contract_Line_Item__c cli = jj_rb_Test_BaseClass.setupRetailerContractLineItem(contract, product);
            insert cli;
            
            // approve the contract
            contract.jj_rb_Status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
            update contract;            
            
            // run the retailer accrual batch process
            //jj_rb_RetailerAccrualCalc batch = new jj_rb_RetailerAccrualCalc();
            //batch.retailer_contract = jj_rb_Test_BaseClass.getRecordTypeId('Retailer Contract', 'jj_rb_Rebate_Contract__c');
            //database.executeBatch(batch);
            jj_rb_Accrual_Actions.executeCalcBatch();               
        }    
     
        Test.stopTest();    
    }
    
    static testMethod void testHomecareAccrualForExistingCustomer()
    {
        User rebateUser = jj_rb_Test_BaseClass.setupUser();       
        
        Test.startTest();
        
        system.runAs(rebateUser) { 
        jj_rb_Test_BaseClass.setupRebateAnalystUser(rebateUser);
        jj_rb_Test_BaseClass.setupRebateNCMUser(rebateUser);
          
        // fill the customset for recordtypes
        List<jj_rb_Master_Data_RecordTypes__c> listCS = jj_rb_Test_BaseClass.createRecordTypeCustomSetting();                                            
        insert listCS;
          
        // create a product
        jj_rb_Rebate_Product__c product = jj_rb_Test_BaseClass.setupRebateProduct();
        insert product;
        
        //String hcpRecordtype = jj_rb_Test_BaseClass.getRecordTypeId('Homecare provider', 'Account');  
        //String recordtype=hcpRecordtype.substring(0,15);  
        
        // create a homecare account
        Account homecare= jj_rb_Test_BaseClass.setupHomecareCustomer(rebateUser);
        homecare.Account_Type__c=jj_rb_Test_BaseClass.accountTypeCreator('Home Care Provider','Homecare');
        homecare.jj_rb_IMS_Customer_Id__c='25698';            
        insert homecare;
                       
       
        List<account> alist=[SELECT Id,jj_rb_IMS_Customer_Id__c,Account_Type__c,jj_rb_National_Channel_Manager__c,jj_rb_SAP_Customer_Number__c,Name,RecordTypeId FROM Account];
        System.assertEquals(1,alist.size());        
        
        // setup region
        jj_rb_Region__c region = jj_rb_Test_BaseClass.setupRegion();
        insert region;
                       
        // set NHS Trust
        Account trust = jj_rb_Test_BaseClass.setupTrustCustomer(region);
        insert trust;
            
        // create hospital
        Account hospital = jj_rb_Test_BaseClass.setupHospital(trust, rebateUser);
        insert hospital;
          
        // setup era
        jj_rb_Estimated_Rebate_Accrual__c era = jj_rb_Test_BaseClass.setupERA(homecare, product); 
        insert era;          
          
          
        // create a homecare claim
        jj_rb_Rebate_Claim__c hcpclaim = jj_rb_Test_BaseClass.setupHCPClaim(homecare);       
        insert hcpclaim;          
          
        // create claim line item
        jj_rb_Rebate_Claim_Line_Item__c claimLI = jj_rb_Test_BaseClass.setupHCPClaimLineItems(hcpclaim, product,hospital);
        insert claimLI;
          
        // approve the claim
        hcpclaim.jj_rb_Status__c = jj_rb_Test_BaseClass.STATUS_APPROVED;
        //hcpclaim.jj_rb_Customer__c=homecare.id;
        update hcpclaim;  
        
                
        jj_rb_HCPAccrualcalc batch= new jj_rb_HCPAccrualcalc();               
        Database.executeBatch(batch);
        batch.execute(null,alist);
                
        //Scheduler
        jj_rb_RebateAccrualCalcScheduler sched = new jj_rb_RebateAccrualCalcScheduler();
        sched.execute(null);                  
          
        }
        Test.stopTest();  
    }
    
    static testMethod void testHomecareAccrualForNewCustomer()
    {
        User rebateUser = jj_rb_Test_BaseClass.setupUser();       
        
        Test.startTest();
        
        system.runAs(rebateUser) { 
        jj_rb_Test_BaseClass.setupRebateAnalystUser(rebateUser);
        jj_rb_Test_BaseClass.setupRebateNCMUser(rebateUser);
          
        // fill the customset for recordtypes
        List<jj_rb_Master_Data_RecordTypes__c> listRecType = jj_rb_Test_BaseClass.createRecordTypeCustomSetting();
        insert listRecType;
          
        // create a product
        jj_rb_Rebate_Product__c product = jj_rb_Test_BaseClass.setupRebateProduct();
        insert product;      
        
         
        
        // create a homecare account
        Account homecares= jj_rb_Test_BaseClass.setupHomecareCustomer(rebateUser);
        homecares.Account_Type__c=jj_rb_Test_BaseClass.accountTypeCreator('Home Care Provider','Homecare');
        homecares.jj_rb_IMS_Customer_Id__c='25698';
       
        insert homecares;        
        
        List<account> alist=[SELECT Id,jj_rb_IMS_Customer_Id__c,Account_Type__c,jj_rb_National_Channel_Manager__c,jj_rb_SAP_Customer_Number__c,Name,RecordTypeId FROM Account];
        System.assertEquals(1,alist.size()); 
        
        // setup region
        jj_rb_Region__c region = jj_rb_Test_BaseClass.setupRegion();
        insert region;
                       
        // set NHS Trust
        Account trust = jj_rb_Test_BaseClass.setupTrustCustomer(region);
        insert trust;
            
        // create hospital
        Account hospital = jj_rb_Test_BaseClass.setupHospital(trust, rebateUser);
        insert hospital;
          
        // setup era
        jj_rb_Estimated_Rebate_Accrual__c era = jj_rb_Test_BaseClass.setupERA(homecares, product); 
        insert era;
          
        jj_rb_Accrual_Actions.executeCalcBatch();             
        }
        Test.stopTest();  
    }
    
    

}