src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>jj_rb_NHS_Trust__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>NHS Trust</label>
        <referenceTo>jj_rb_NHS_Trust__c</referenceTo>
        <relationshipLabel>Hospitals</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_National_Channel_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>National Channel Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_SAP_Customer_Number__c</fullName>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>jj_rb_SAP_Vendor_Number__c</fullName>
        <label>SAP Vendor Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/jj_rb_NHS_Trust__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Business_City__c</fullName>
        <label>Business City</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>jj_rb_NHS_Trust_ID__c</fullName>
        <externalId>true</externalId>
        <label>NHS Trust ID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>jj_rb_Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Region</label>
        <referenceTo>jj_rb_Region__c</referenceTo>
        <relationshipLabel>NHS Trusts</relationshipLabel>
        <relationshipName>NHS_Trusts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>NHS Trust</label>
    <nameField>
        <label>NHS Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NHS Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Permission_Set__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>List of Permission Sets for UK Rebate application.</description>
    <fields>
        <fullName>jj_rb_Permission_Set_Id__c</fullName>
        <description>Id of Rebate related permission set</description>
        <label>Permission Set Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>UK Rebate Permission Set</label>
</CustomObject>

src/objects/jj_rb_Rebate_Product__c.object
<CustomObject>
    <description>Information of the products sold to Retailers and homecare providers are stored here. A separate custom object created for products, as this application is a potential candidate for migration to iConnect and to minimize the impact on the standard Product object in iConnect.</description>
    <fields>
        <fullName>jj_rb_Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>jj_rb_SAP_EAN_Code__c</fullName>
        <description>SKU Number of the product from SAP.</description>
        <externalId>true</externalId>
        <label>SAP EAN Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>jj_rb_SAP_Material_Number__c</fullName>
        <description>Material No of the product from SAP</description>
        <externalId>true</externalId>
        <label>SAP Material No</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>jj_rb_VAT_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VAT Code</label>
        <referenceTo>jj_rb_VAT_Code__c</referenceTo>
        <relationshipLabel>Rebate Products</relationshipLabel>
        <relationshipName>Rebate_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rebate Product</label>
    <nameField>
        <label>Rebate Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rebate Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/jj_rb_Region__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/jj_rb_VAT_Code__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_VAT_External_Id__c</fullName>
        <description>External Id for dataloader</description>
        <externalId>true</externalId>
        <label>VAT External Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>jj_rb_VAT__c</fullName>
        <label>VAT %</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>VAT Code</label>
    <nameField>
        <label>VAT Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VAT Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/jj_rb_Test_BaseClass.cls
public class jj_rb_Test_BaseClass {
	public static Account setupHomecareCustomer(User ncmUser)
    {
    	Id hcpRecordtype = getRecordTypeId('Homecare provider', 'Account');
    	
    	Account a = new Account();
    	a.jj_rb_National_Channel_Manager__c = ncmUser.Id;
    	a.jj_rb_SAP_Customer_Number__c = '221';
    	a.jj_rb_SAP_Vendor_Number__c = '221';
    	a.RecordTypeId = hcpRecordtype; 
		a.Name = 'test Account';
		
    	insert a;
    	return a;
    	
    }
    
    public static jj_rb_Rebate_Product__c setupRebateProduct()
    {
    	jj_rb_VAT_Code__c vatCode = setupVATCode();
    	
    	jj_rb_Rebate_Product__c product = new jj_rb_Rebate_Product__c();
    	product.jj_rb_SAP_EAN_Code__c = '376769';
    	product.jj_rb_SAP_Material_Number__c = '376769';
    	product.Name = 'Test Product';
    	product.jj_rb_Description__c = 'Product description';
    	product.jj_rb_VAT_Code__c = vatCode.id;
    	
    	insert product;
    	return product;
    }
    
    public static Account setupHospital(jj_rb_NHS_Trust__c trust, User ncmUser)
    {
    	Id hospitalRecordtype = getRecordTypeId('Hospital_vod', 'Account');
    	Account a = new Account();
    	a.jj_rb_NHS_Trust__c = trust.id;
    	a.CODS_External_Id__c = '12345';
    	a.RecordTypeId = hospitalRecordtype;
    	a.name = 'Test Hospital';
    	
    	
    	if(ncmUser != null)
    		a.jj_rb_National_Channel_Manager__c = ncmUser.Id;
   
    	insert a;
    	return a;
    	
    }
    
    public static jj_rb_VAT_Code__c setupVATCode()
    {
    	jj_rb_VAT_Code__c vat = new jj_rb_VAT_Code__c();
    	vat.jj_rb_VAT__c = 20;
    	vat.jj_rb_VAT_External_Id__c = '20';
    	vat.Name = 'test vat';
    	
    	insert vat;
    	return vat;
    }
    
    public static jj_rb_NHS_Trust__c setupTrust(jj_rb_Region__c r)
    {
    	jj_rb_NHS_Trust__c t = new jj_rb_NHS_Trust__c();
    	t.Name = 'Test Trust';
    	t.jj_rb_NHS_Trust_ID__c = '12345';
    	t.jj_rb_Business_Phone__c = '12312344123';
    	t.jj_rb_Business_Postal_Code__c = '1234567';
    	t.jj_rb_Business_Street__c = 'trust street';
    	t.jj_rb_Business_City__c = 'trust city';
    	t.jj_rb_Region__c = r.Id;
    	insert t;
    	return t;
    }
    
    // create a test region
    public static jj_rb_Region__c setupRegion()
    {
    	jj_rb_Region__c r = new jj_rb_Region__c();
    	r.jj_rb_Description__c = 'test region';
    	r.Name = 'TestRegion';
    	insert r;
    	return r;
    }
    
    
    
    public static Id getRecordTypeId(String recordTypeName, String objectName)
    {
    	List<RecordType> r = [select Id from RecordType 
    								where name = :recordTypeName 
    								and SobjectType = :objectName limit 1];
    	if(!r.isEmpty())
    		return r[0].Id;
    	return null;	
    }
    
    public static User setupRebateNCMUser(User u)
    {
    	// get rebate analyst permission set
    	List<PermissionSet> permissionSetNCM = [select Id from PermissionSet where name = 'jj_rb_UK_Rebate_NCM' limit 1];
    	    	
    	if(!permissionSetNCM.isEmpty())
    	{
    		//return getUser(permissionSetNCM[0].Id);
    		PermissionSetAssignment pa = new PermissionSetAssignment();
	    	pa.AssigneeId = u.Id;
	    	pa.PermissionSetId =  permissionSetNCM[0].Id;	
	    	insert pa;												
    	}
    	return null;	
    }
    
    public static User getUser(String permissionSetId)
    {
    	if(String.isNotBlank(permissionSetId))
    	{
    		List<User> listUser = [select Id from User 
    								where isActive = true 
    								and id in (SELECT AssigneeId 
    												FROM PermissionSetAssignment where PermissionSetId = :permissionSetId) limit 1];    		
    		
    		
    		if(!listUser.isEmpty())
    			return listUser[0];	
    	}
    	return null;
    }
    
    public static User setupRebateAnalystUser(User u)
    {
    	// get rebate analyst permission set
    	List<PermissionSet> permissionSetAnalyst = [select Id from PermissionSet where name = 'jj_rb_UK_Rebate_Analyst' limit 1];
    	if(!permissionSetAnalyst.isEmpty())
    	{
    		//return getUser(permissionSetAnalyst[0].Id);    		
    		PermissionSetAssignment pa = new PermissionSetAssignment();
	    	pa.AssigneeId = u.Id;
	    	pa.PermissionSetId =  permissionSetAnalyst[0].Id;	
	    	insert pa;    														
    	}
    	return null;
    }
    
    public Static User setupUser()
    {
    	Profile prof = [select id from profile where name = 'System Administrator'];
        User u = new User(alias = 'standt', email = 'testFeedItemDelete@testorg.com', emailencodingkey = 'UTF-8', lastname = 'Testing', languagelocalekey = 'en_US', localesidkey = 'en_US', profileid = prof.Id, timezonesidkey = 'America/Los_Angeles', username = 'testFeedItemDelete@testorg.com');
        insert u;
        return u;
    }
    
    public static void setupCustomSettings()
    {
    	// set the custom setting  for permission set
    	List<jj_rb_Rebate_Permission_Set__c> listPermissionSetCustomSetting = new List<jj_rb_Rebate_Permission_Set__c>();
    	List<PermissionSet> listPermissionSet = [select Id, name  from PermissionSet where name like 'jj_rb_UK_Rebate_%'];
    	for(PermissionSet pm : listPermissionSet) {
    		jj_rb_Rebate_Permission_Set__c rps = new jj_rb_Rebate_Permission_Set__c();
    		rps.name = pm.name;
    		rps.jj_rb_Permission_Set_Id__c = pm.id;
    		listPermissionSetCustomSetting.add(rps);
    	}
    	if(!listPermissionSetCustomSetting.isEmpty())
    		insert listPermissionSetCustomSetting;
    	
    }
    

}