src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>jj_rb_IMS_Customer_Id__c</fullName>
        <externalId>true</externalId>
        <label>IMS Customer Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>jj_rb_National_Channel_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>National Channel Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_SAP_Customer_Number__c</fullName>
        <externalId>true</externalId>
        <label>SAP Customer Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>jj_rb_SAP_Vendor_Number__c</fullName>
        <label>SAP Vendor Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/jj_rb_Estimated_Rebate_Accrual__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Estimate_Rebate_Accruals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Estimated_Accrual__c</fullName>
        <label>Estimated Accrual</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rebate Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipName>Estimate_Rebate_Accruals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Estimated Rebate Accrual</label>
    <nameField>
        <displayFormat>ERA-{000}</displayFormat>
        <label>Estimated Rebate Accrual Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimated Rebate Accruals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Accrual__c.object
<CustomObject>
    <description>The information generated from the monthly execution of the rebate accruals is stored here.</description>
    <fields>
        <fullName>jj_rb_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer for whom the rebate accrual record is created.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rebate Accruals</relationshipLabel>
        <relationshipName>Rebate_Accruals_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Accrual</label>
    <nameField>
        <displayFormat>RA-{000}</displayFormat>
        <label>Rebate Accrual Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Accruals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Accrual_Line_Item__c.object
<CustomObject>
    <description>Product line items present in the Rebate accrual form.</description>
    <fields>
        <fullName>jj_rb_Rebate_Accrual__c</fullName>
        <description>Master Rebate accrual for which these line items are created.</description>
        <label>Rebate Accrual</label>
        <referenceTo>jj_rb_Rebate_Accrual__c</referenceTo>
        <relationshipLabel>Rebate Accrual Line Item</relationshipLabel>
        <relationshipName>Rebate_Accrual_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rebate Accrual Line Item</label>
    <nameField>
        <displayFormat>RALI-{000}</displayFormat>
        <label>Rebate Accrual Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Accrual Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Claim__c.object
<CustomObject>
    <description>This object will store the claim invoice submitted by the customer.</description>
    <fields>
        <fullName>jj_rb_Claim_Date__c</fullName>
        <formula>DATE(value(text(jj_rb_Year__c)) ,value(text(jj_rb_Month__c)) ,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Claim Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>jj_rb_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rebate Claims</relationshipLabel>
        <relationshipName>Rebate_Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Claim</label>
    <nameField>
        <displayFormat>CL-{0}</displayFormat>
        <label>Rebate Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Claim_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Hospital__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated hospital lookup field</description>
        <label>Hospital</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Net_Rebate__c</fullName>
        <formula>jj_rb_Quantity__c *  jj_rb_Rebate_Per_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Rebate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>jj_rb_Quantity__c</fullName>
        <description>Quantity of the product</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Claim__c</fullName>
        <label>Rebate Claim</label>
        <referenceTo>jj_rb_Rebate_Claim__c</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product for which rebate is being claimed.</description>
        <label>Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Rebate Claim Line Item</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Rebate Claim Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Claim Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Product__c.object
<CustomObject>
    <description>Information of the products sold to Retailers and homecare providers are stored here. A separate custom object created for products, as this application is a potential candidate for migration to iConnect and to minimize the impact on the standard Product object in iConnect.</description>
    <label>Rebate Product</label>
    <nameField>
        <label>Rebate Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rebate Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/jj_rb_HCPAccrualcalc.cls
global class jj_rb_HCPAccrualcalc extends jj_rb_rebateAccrualBaseClass implements Database.batchable<sObject> 
{
     static id hcpRecordtypeID = jj_rb_rebate_utils.getRecordTypeId('Account_Homecare');
     
     global Database.QueryLocator start(Database.BatchableContext BC)
     {
         String query = 'SELECT Id,jj_rb_IMS_Customer_Id__c,Account_Type__c,jj_rb_National_Channel_Manager__c,jj_rb_SAP_Customer_Number__c,Name,RecordTypeId FROM Account where RecordTypeID =: hcpRecordtypeID'; 
            return Database.getQueryLocator(query);
     }
     
     
     global void execute(Database.BatchableContext BC, List<sObject> scope){    
     Map<Id, List<jj_rb_Rebate_Claim__c>> mapCustClaims = new Map<Id,List<jj_rb_Rebate_Claim__c>>();   // key -> cust id
     Map<Id, List<jj_rb_Estimated_Rebate_Accrual__c>> mapEstimatedAccruals = new Map<Id, List<jj_rb_Estimated_Rebate_Accrual__c>> ();   // key -> cust id         
     system.debug('********** '+scope);
     Map<Id, jj_rb_Rebate_Accrual__c> mapRebateAccrual = new Map<Id, jj_rb_Rebate_Accrual__c>();    // key -> cust id
     Map<Id, List<jj_rb_Rebate_Accrual_Line_Item__c>> mapRebateAccrualLI = new Map<Id, List<jj_rb_Rebate_Accrual_Line_Item__c>>();  // key -> cust Id
     Set<Id> setCustomerId = new Set<Id>(); 
     List<Account> listAccount = new List<Account>();     
    
     String Account_HCP = jj_rb_Rebate_utils.getRecordTypeId('Account_Homecare');
     String Accrual_HCP = jj_rb_Rebate_utils.getRecordTypeId('Accrual_Homecare');
     String HCPType = jj_rb_Rebate_utils.getAccountType('Home Care Provider');
     id Homecare_claim = jj_rb_Rebate_utils.getRecordTypeId('Claim_Homecare');
     // create a set of customer Id
     for(Account acc : (List<Account>) scope)
     {
         if(acc.Account_Type__c == HCPType )
         {
            setCustomerId.add(acc.id);
            listAccount.add(acc);
         }
     }
     
    /* List<Account> listAccount = [select Id,Name, jj_rb_National_Channel_Manager__c,
                                         jj_rb_SAP_Customer_Number__c, jj_rb_SAP_Vendor_Number__c 
                                        from Account where id in :setCustomerId];
     
     */
     // get the estimated rebate accrual values for the customer
     for(jj_rb_Estimated_Rebate_Accrual__c estimatedAccruals : [select Id, Name,jj_rb_Estimated_Accrual__c,
                                                                    jj_rb_Rebate_Product__c, jj_rb_Account__c
                                                                    from jj_rb_Estimated_Rebate_Accrual__c
                                                                    where jj_rb_Account__c in :setCustomerId])
     {    
        List<jj_rb_Estimated_Rebate_Accrual__c> listEstimatedAccruals = new List<jj_rb_Estimated_Rebate_Accrual__c>();
        if (mapEstimatedAccruals.containsKey(estimatedAccruals.jj_rb_Account__c))
        {
            listEstimatedAccruals = mapEstimatedAccruals.get(estimatedAccruals.jj_rb_Account__c);
        } 
        listEstimatedAccruals.add(estimatedAccruals);
        mapEstimatedAccruals.put(estimatedAccruals.jj_rb_Account__c, listEstimatedAccruals);
     }
     system.debug('mapEstimatedAccruals>>>>' + mapEstimatedAccruals);  
     
     // loop over claims and create a map with last 3 claims of the customer "super class"
     for(jj_rb_Rebate_Claim__c claim : [SELECT Id, Name, jj_rb_Claim_Date__c, jj_rb_Customer__c, 
                                                (select id, name, jj_rb_Rebate_Product__c, jj_rb_Quantity__c,
                                                        jj_rb_Net_Rebate__c from Rebate_Claim_Line_Items__r) 
                                                 FROM jj_rb_Rebate_Claim__c 
                                                 where jj_rb_Claim_Date__c = LAST_N_DAYS:730 
                                                       and recordtypeid =: Homecare_claim  
                                                       and jj_rb_Status__c = 'Approved'
                                                       and jj_rb_Claim_Date__c < THIS_MONTH
                                                       order by jj_rb_Claim_Date__c desc])
     {
        String customerId = claim.jj_rb_Customer__c;
        if(mapCustClaims.containsKey(customerId))
        {
            List<jj_rb_Rebate_Claim__c> listClaims = mapCustClaims.get(customerId);
            if(listClaims != null && listClaims.size() <=2)
            {
                listClaims.add(claim);
                mapCustClaims.put(customerId, listClaims);
            }
        } else {
            List<jj_rb_Rebate_Claim__c> listClaims = new List<jj_rb_Rebate_Claim__c>{claim};
            mapCustClaims.put(customerId, listClaims);
        }
     }                                                             
     
     // loop over each customer 
     for(Account customer : listAccount) 
     {
        String customerId = customer.Id;
        system.debug('customer - ' + customer.Name + ' with customer Id - ' + customerId);
        
        List<jj_rb_Rebate_Claim__c> listClaims = mapCustClaims.get(customerId);        
        if(listClaims != null && !listClaims.isEmpty())
        {           
            system.debug('claim  found for this customer>>>>>'  + listClaims);
            calcAccrualForExistingCustomer(customer, listClaims, mapRebateAccrual, mapRebateAccrualLI,Accrual_HCP);
        }
        else
        {
            system.debug('No claim line items for this customer>>>>>');
            processAccrualForNewCustomer(customer, mapEstimatedAccruals, mapRebateAccrual, mapRebateAccrualLI,Accrual_HCP); 
        }       
        
     } 
     
     // create the rebate accrual and rebate accrual Line Item record
     createAccruals(mapRebateAccrual, mapRebateAccrualLI);    
 }
 global void finish(Database.BatchableContext BC){   
       
 }
}