src/objects/jj_rb_Rebate_Contract__c.object
<CustomObject>
    <description>This object stores the contract information created for a customer.</description>
    <fields>
        <fullName>jj_rb_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rebate Contracts</relationshipLabel>
        <relationshipName>Rebate_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipLabel>Rebate Contracts</relationshipLabel>
        <relationshipName>Rebate_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Contract</label>
    <nameField>
        <displayFormat>RC-{0}</displayFormat>
        <label>Rebate Contract No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Product__c.object
<CustomObject>
    <description>Information of the products sold to Retailers and homecare providers are stored here. A separate custom object created for products, as this application is a potential candidate for migration to iConnect and to minimize the impact on the standard Product object in iConnect.</description>
    <label>Rebate Product</label>
    <nameField>
        <label>Rebate Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rebate Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/jj_rb_EditcontractOverrideclass.cls
public with sharing class jj_rb_EditcontractOverrideclass{
     public ApexPages.StandardController controller;
     public jj_rb_Rebate_Contract__c contracts;
     public string recordtype{set;get;}
     public String retURL {get; set;}
     public string status{set;get;}
     public string customer{set;get;}
     public string contract{set;get;}
     public string product{set;get;}
     
     //Record Types
      
     String retailercontract_recordType=jj_rb_Rebate_utils.getRecordTypeId('Retailer Contract');
     String HomecareContract_recordType=jj_rb_Rebate_utils.getRecordTypeId('Home care Provider contract');   
     
     
     String Status_Expired=jj_rb_Rebate_utils.getRebateLineItemStatus('Expired');    
     //constructor
     public jj_rb_EditcontractOverrideclass(ApexPages.StandardController controller)
     {
        this.controller=controller;
        status=ApexPages.currentPage().getParameters().get('contracts.jj_rb_Status__c');
        recordtype=ApexPages.currentPage().getParameters().get('contracts.RecordType.name');
        customer=ApexPages.currentPage().getParameters().get('contracts.jj_rb_customer__r.name');
        contract=ApexPages.currentPage().getParameters().get('contracts.name');
        product=ApexPages.currentPage().getParameters().get('contracts.jj_rb_Product__r.name');
        retURL = ApexPages.currentPage().getParameters().get('retURL');     
     
     }
     public Pagereference Edit()
    {
        PageReference returnURL;
        contracts=(jj_rb_Rebate_Contract__c)controller.getRecord();
        //get the Rebate contracts 
        contracts=[select jj_rb_Status__c,name,RecordTypeId,RecordType.name,jj_rb_Product__r.name,
                        jj_rb_customer__c,jj_rb_Customer__r.name from jj_rb_Rebate_Contract__c
                        where id=:contracts.id];
        if(contracts.jj_rb_Status__c==Status_Expired && contracts.RecordTypeId==retailercontract_recordType)
        {
            returnURL=new PageReference('/apex/jj_rb_contractEditOverrideforRetailer?id='+contracts.id);        
        
        } else if(contracts.jj_rb_Status__c==Status_Expired && contracts.RecordTypeId==HomecareContract_recordType)
        {
            returnURL=new PageReference('/apex/jj_rb_contractEditOverrideforHomecare?id='+contracts.id);     
        }else        
        {           
            returnURL=new PageReference('/'+contracts.id+'/e?nooverride=1');           
        }
        returnURL.getParameters().put('retURL',retURL ); 
        returnURL.getParameters().put('recordtype',contracts.RecordType.name);
        returnURL.getParameters().put('Status',contracts.jj_rb_Status__c);       
        returnURL.getParameters().put('customer',contracts.jj_rb_customer__r.name); 
        returnURL.getParameters().put('contract',contracts.name); 
        returnURL.getParameters().put('product',contracts.jj_rb_Product__r.name);           
        returnURL.getParameters().put('nooverride', '1');
        
        returnURL.setRedirect(true);
        

    return returnURL;
    }
     




}