src/objects/jj_rb_Rebate_SAP_Job__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Notification_Email__c</fullName>
        <defaultValue>$User.Email</defaultValue>
        <description>Email address to which a notification email will be sent upon SAP job completion</description>
        <inlineHelpText>Email address to which a notification email will be sent upon SAP job completion</inlineHelpText>
        <label>Notification Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <description>Status of the job</description>
        <inlineHelpText>Status of the job - jobs in &quot;Ready&quot; state can be processed</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate SAP Job</label>
    <nameField>
        <displayFormat>RBSAP-{0000}</displayFormat>
        <label>Rebate SAP Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate SAP Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/jj_rb_UploadSAPDataController.cls
public with sharing class jj_rb_UploadSAPDataController {
    public jj_rb_UploadSAPDataController(ApexPages.StandardController controller) {

    }
    Public Attachment myfile;
    Public Attachment getmyfile()
    {
        myfile = new Attachment();
        return myfile;
    }
   
    Public Pagereference Savedoc()
    {
		
		String emailAddress = UserInfo.getUserEmail();
		jj_rb_Rebate_SAP_Job__c job = new jj_rb_Rebate_SAP_Job__c();
		job.jj_rb_Notification_Email__c = emailAddress;
  		job.jj_rb_Status__c = 'Ready';
  		insert job;
  		
        Attachment a = new Attachment(parentId = job.Id, name=myfile.name, body = myfile.body);
         
        /* insert the attachment */
        insert a;
        
        jj_rb_SAP_Job_Submit.ProcessJob(job.Id);
        
        
        String ObjectPrefix = jj_rb_Rebate_SAP_Job__c.sObjectType.getDescribe().getKeyPrefix();
              
        PageReference p = new PageReference('/'+ObjectPrefix);
        p.setRedirect(true);
  
        return p;  
    }   

}