src/objects/jj_rb_Rebate_SAP_Job__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Notification_Email__c</fullName>
        <defaultValue>$User.Email</defaultValue>
        <description>Email address to which a notification email will be sent upon SAP job completion</description>
        <inlineHelpText>Email address to which a notification email will be sent upon SAP job completion</inlineHelpText>
        <label>Notification Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>jj_rb_Remaining_Files__c</fullName>
        <description>Number of files that still have to be processed, populated by the APEX logic loading the files</description>
        <inlineHelpText>Number of files that still have to be processed, populated by the APEX logic loading the files</inlineHelpText>
        <label>Remaining Files</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <description>Status of the job</description>
        <inlineHelpText>Status of the job - jobs in &quot;Ready&quot; state can be processed</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate SAP Job</label>
    <nameField>
        <displayFormat>RBSAP-{0000}</displayFormat>
        <label>Rebate SAP Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate SAP Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/jj_rb_SAP_Job_Submit.cls
/**
 *      @author Bart Geens
 *      @date   22/04/2014
        @description    Class for handling validation steps before submitting an SAP loading job

        Modification Log:
        ------------------------------------------------------------------------------------------------------
        Developer					Date				Description
        ------------------------------------------------------------------------------------------------------
        Bart Geens				22/04/2014			Original Version 
 */
 
global with sharing class jj_rb_SAP_Job_Submit {
    WebService static String ProcessJob(Id JobId)
    {
    	
    	Datetime myDateTime = Datetime.now();
		jj_rb_Rebate_SAP_Job__c oJob = [select Id, Name, jj_rb_Status__c, jj_rb_Notification_Email__c from jj_rb_Rebate_SAP_Job__c where jj_rb_Status__c = 'Ready' and Id=:JobId];
		//jj_rb_SAP_Load__c oJob = [select Id, Name, jj_rb_Status__c, jj_rb_Notification_Email__c from jj_rb_SAP_Load__c where Id=:JobId];
		//Get csv attachments linked to this ATL job
		List<Attachment> lAttachments = [select Id, Name, Body from Attachment Where ParentId = :JobId And Name like '%csv'];
		 
		//If no error message is returned job is concidered to be valid
		String sValidationResult = ValidateJob(oJob);
		
		if(sValidationResult == '')
		{
			//Set job in progress
			oJob.jj_rb_Status__c = 'In Progress';
			oJob.jj_rb_Remaining_Files__c = lAttachments.size();
			update oJob;
			 
			//Create map with files
			Map<String, String> mSAPFiles = new Map<String, String>();
			 
			for(Attachment oAttachment : lAttachments) {
			       mSAPFiles.put(oAttachment.Name, oAttachment.body.toString());
			}
			 
			jj_rb_SAP_Job_Async oATLJob = new jj_rb_SAP_Job_Async(oJob.Id, oJob.Name, oJob.jj_rb_Notification_Email__c, mSAPFiles);
			Database.executeBatch(oATLJob);
		} 

		return sValidationResult;
    }
    
    private static String ValidateJob(jj_rb_Rebate_SAP_Job__c theJob)
    {
		//Get all attachments linked to this SAP job
		List<Attachment> lAttachments = [select Id, Name, Body from Attachment Where ParentId = :theJob.Id And Name like '%csv'];
		
		if(lAttachments.size() > 0) {		
    		return '';
		} else {
			return 'At least one csv file has to be linked to the job to be able to proceed';
		}
    }
}