src/objects/jj_rb_Rebate_Accrual__c.object
<CustomObject>
    <description>The information generated from the monthly execution of the rebate accruals is stored here.</description>
    <fields>
        <fullName>jj_rb_Accrual_Date__c</fullName>
        <formula>DATE( value(text(jj_rb_Year__c)) ,value(text( jj_rb_Month__c )),1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Accrual Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>jj_rb_Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Accrual</label>
    <nameField>
        <displayFormat>RA-{000}</displayFormat>
        <label>Rebate Accrual Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Accruals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Accrual_Line_Item__c.object
<CustomObject>
    <description>Product line items present in the Rebate accrual form.</description>
    <fields>
        <fullName>jj_rb_Net_Rebate_Accrual_After_Adj__c</fullName>
        <formula>jj_rb_Net_Rebate_Accrual_Amount__c  +  Rebate_Adjustment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Rebate Accrual After Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>jj_rb_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipLabel>Rebate Accrual Line Item</relationshipLabel>
        <relationshipName>Rebate_Accrual_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Accrual__c</fullName>
        <description>Master Rebate accrual for which these line items are created.</description>
        <label>Rebate Accrual</label>
        <referenceTo>jj_rb_Rebate_Accrual__c</referenceTo>
        <relationshipLabel>Rebate Accrual Line Item</relationshipLabel>
        <relationshipName>Rebate_Accrual_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Rebate Accrual Line Item</label>
    <nameField>
        <displayFormat>RALI-{000}</displayFormat>
        <label>Rebate Accrual Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Accrual Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Accrual_Report__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes if the report preparation is complete.</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>jj_rb_Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2024</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2026</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2027</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2028</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2029</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2030</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Accrual Report</label>
    <nameField>
        <displayFormat>R-{0}</displayFormat>
        <label>Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Accrual Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Accrual_Report_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Net_Rebate__c</fullName>
        <label>Net Rebate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>jj_rb_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Accrual_Report__c</fullName>
        <label>Rebate Accrual Report</label>
        <referenceTo>jj_rb_Rebate_Accrual_Report__c</referenceTo>
        <relationshipLabel>Rebate Accrual Report Line Items</relationshipLabel>
        <relationshipName>Rebate_Accrual_Report_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rebate Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipLabel>Rebate Accrual Report Line Items</relationshipLabel>
        <relationshipName>Rebate_Accrual_Report_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rebate Accrual Report Line Item</label>
    <nameField>
        <displayFormat>RLI-{0}</displayFormat>
        <label>Report Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Accrual Report Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Product__c.object
<CustomObject>
    <description>Information of the products sold to Retailers and homecare providers are stored here. A separate custom object created for products, as this application is a potential candidate for migration to iConnect and to minimize the impact on the standard Product object in iConnect.</description>
    <label>Rebate Product</label>
    <nameField>
        <label>Rebate Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rebate Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/jj_rb_Accrual_Report_Generation.cls
global class jj_rb_Accrual_Report_Generation implements Database.batchable<sObject>, Database.Stateful{
    global Map<id,Map<String, jj_rb_Rebate_Accrual_Report_Line_Item__c>> mapAccrualMain = 
                                                               new Map<id, Map<String, jj_rb_Rebate_Accrual_Report_Line_Item__c>>();    // outer key -> accrual recordtype id and inner key -> product id
    
    global  Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'select Id, jj_rb_Product__c, jj_rb_Net_Rebate_Accrual_After_Adj__c, jj_rb_Volume__c,jj_rb_Rebate_Accrual__r.RecordTypeId from jj_rb_Rebate_Accrual_Line_Item__c where jj_rb_Rebate_Accrual__r.jj_rb_Status__c = \'Approved\' and jj_rb_Rebate_Accrual__r.jj_rb_Accrual_Date__c = this_month order by jj_rb_Product__c';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        for(jj_rb_Rebate_Accrual_Line_Item__c accrualLineItem : (List<jj_rb_Rebate_Accrual_Line_Item__c>) scope)
        {
            String accrualRecordType = accrualLineItem.jj_rb_Rebate_Accrual__r.RecordTypeId;
            
            Map<String, jj_rb_Rebate_Accrual_Report_Line_Item__c> mapReportLineItems;
            if(mapAccrualMain.containsKey(accrualRecordType))
            {
                mapReportLineItems = mapAccrualMain.get(accrualRecordType);              
            } else {
                // create the map of report line items 
                mapReportLineItems =  new Map<String, jj_rb_Rebate_Accrual_Report_Line_Item__c>();              
            }
            mapReportLineItems = getReportLineItemsMap(accrualLineItem, mapReportLineItems);
            mapAccrualMain.put(accrualRecordType, mapReportLineItems);      
                
        }       
    }
    
    private Map<String, jj_rb_Rebate_Accrual_Report_Line_Item__c> getReportLineItemsMap(jj_rb_Rebate_Accrual_Line_Item__c accrualLineItem,
                                                                                    Map<String, jj_rb_Rebate_Accrual_Report_Line_Item__c> mapReportLineItems)
    {
        
            jj_rb_Rebate_Accrual_Report_Line_Item__c reportLineItem;
            if(mapReportLineItems.containsKey(accrualLineItem.jj_rb_Product__c))
            {
                reportLineItem = mapReportLineItems.get(accrualLineItem.jj_rb_Product__c);
                reportLineItem.jj_rb_Net_Rebate__c +=  accrualLineItem.jj_rb_Net_Rebate_Accrual_After_Adj__c;
                reportLineItem.jj_rb_Quantity__c += accrualLineItem.jj_rb_Volume__c;                
            } else {
                reportLineItem = new jj_rb_Rebate_Accrual_Report_Line_Item__c();
                reportLineItem.jj_rb_Rebate_Product__c = accrualLineItem.jj_rb_Product__c;
                reportLineItem.jj_rb_Net_Rebate__c = accrualLineItem.jj_rb_Net_Rebate_Accrual_After_Adj__c;
                reportLineItem.jj_rb_Quantity__c = accrualLineItem.jj_rb_Volume__c;                            
            }   
            mapReportLineItems.put(accrualLineItem.jj_rb_Product__c, reportLineItem);
        return mapReportLineItems;
    }                                                                                    
    
    global void finish(Database.BatchableContext BC){  
   
        String RetailerAccrualRecordType = jj_rb_Rebate_utils.getRecordTypeId('Accrual_Retailer');
        String HCPAccrualRecordType = jj_rb_Rebate_utils.getRecordTypeId('Accrual_Homecare');
        String RetialerReportType = jj_rb_Rebate_utils.getRecordTypeId('Accrual_Report_Retailer');
        String HCPReportType = jj_rb_Rebate_utils.getRecordTypeId('Accrual_Report_Homecare');
        
        Map<String, jj_rb_Rebate_Accrual_Report_Line_Item__c> mapLineItems;
        
        list <jj_rb_Rebate_Accrual_Report__c> listaccReport = new list<jj_rb_Rebate_Accrual_Report__c>();
         
       if(!mapAccrualMain.isEmpty())
       {
            // loop over main map and for each key create a report
            for(id accrualRecordType : mapAccrualMain.keySet()) 
            {
                mapLineItems = mapAccrualMain.get(accrualRecordType);
                
                // create a rebate accrual report record 
                jj_rb_Rebate_Accrual_Report__c accrualReport = new jj_rb_Rebate_Accrual_Report__c();
                accrualReport.jj_rb_Month__c = DateTime.now().format('MM');
                accrualReport.jj_rb_Year__c = DateTime.now().format('YYYY');
                id recID = accrualRecordType;
                id RetailerID = RetailerAccrualRecordType;
                accrualReport.RecordTypeId = (accrualRecordType == RetailerAccrualRecordType) ?  RetialerReportType :HCPReportType;
                
                insert accrualReport;
                
                // associate the rebate accrual report with the line items
                for(jj_rb_Rebate_Accrual_Report_Line_Item__c reportLineItem : mapLineItems.values())
                {
                    reportLineItem.jj_rb_Rebate_Accrual_Report__c = accrualReport.Id;
                }
                insert mapLineItems.values();
                
                // mark the rebate accrual report as completed
                accrualReport.jj_rb_Completed__c = true;
                update  accrualReport;  
            }                 
       }
    }
    
   
}