src/objects/jj_rb_Rebate_Claim__c.object
<CustomObject>
    <description>This object will store the claim invoice submitted by the customer.</description>
    <fields>
        <fullName>jj_rb_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Claim</label>
    <nameField>
        <displayFormat>CL-{0}</displayFormat>
        <label>Rebate Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/jj_rb_Claimsubmit_Approval.cls
global class jj_rb_Claimsubmit_Approval
{
    webservice static void Submitforapproval(list<id> listClaim)
    {
    	string statusApproved = jj_rb_Rebate_utils.getRebateLineItemStatus('Approved');
    	string statusSubmitted = jj_rb_Rebate_utils.getRebateLineItemStatus('Submitted');
    	//system.debug('******* List of claims '+listClaim);
        List<jj_rb_rebate_claim__C> listclaimrec = [select id,name,jj_rb_Description__c,jj_rb_Status__c from jj_rb_rebate_claim__c where id IN : listClaim and jj_rb_Status__c Not IN ('Approved','Submitted')];
        //System.debug('**************** selected new records ****** '+listclaimrec);
        
        for(jj_rb_rebate_claim__C claimrec : listclaimrec)
        {
        	Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
       		req.setObjectId(claimrec.id);  
       		Approval.ProcessResult result = Approval.process(req);	
        }   
    }
}