src/objects/jj_rb_Rebate_Claim__c.object
<CustomObject>
    <description>This object will store the claim invoice submitted by the customer.</description>
    <fields>
        <fullName>jj_rb_Claim_Date__c</fullName>
        <formula>DATE(value(text(jj_rb_Year__c)) ,value(text(jj_rb_Month__c)) ,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Claim Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>jj_rb_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rebate Claims</relationshipLabel>
        <relationshipName>Rebate_Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Claim</label>
    <nameField>
        <displayFormat>CL-{0}</displayFormat>
        <label>Rebate Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Claim_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Quantity__c</fullName>
        <description>Quantity of the product</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Claim__c</fullName>
        <label>Rebate Claim</label>
        <referenceTo>jj_rb_Rebate_Claim__c</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Rebate_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product for which rebate is being claimed.</description>
        <label>Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipLabel>Rebate Claim Line Items</relationshipLabel>
        <relationshipName>Rebate_Claim_Line_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Rebate Claim Line Item</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Rebate Claim Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Claim Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Product__c.object
<CustomObject>
    <description>Information of the products sold to Retailers and homecare providers are stored here. A separate custom object created for products, as this application is a potential candidate for migration to iConnect and to minimize the impact on the standard Product object in iConnect.</description>
    <label>Rebate Product</label>
    <nameField>
        <label>Rebate Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rebate Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/jj_rb_Tolerance__c.object
<CustomObject>
    <description>This Object stores Tolerance Details</description>
    <fields>
        <fullName>jj_rb_Average_Quantity__c</fullName>
        <label>Average Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>jj_rb_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tolerance</relationshipLabel>
        <relationshipName>Tolerance</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Price_Tolerance__c</fullName>
        <label>Price Tolerance</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>jj_rb_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>jj_rb_Rebate_Product__c</referenceTo>
        <relationshipLabel>Tolerance</relationshipLabel>
        <relationshipName>Tolerance</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>jj_rb_Quantity_Tolerance__c</fullName>
        <label>Quantity Tolerance</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tolerance</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Tolerance No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tolerance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/jj_rb_avgQuantityCalc.cls
/**
 *    @author  MangaDivya Kasani
 *    @date  15/04/2014
     @description  This class is used to calculate Average Quantity for customer  
      
     Modification Log:
     ------------------------------------------------------------------------------------
     Developer              Date            Description
     ------------------------------------------------------------------------------------
     MangaDivya Kasani    15/04/2014      Original Version
 */
global class jj_rb_avgQuantityCalc implements Database.Batchable<sObject>
{
    
    String homecareclaim_recType=jj_rb_Rebate_utils.getRecordTypeID('Claim_Homecare');
    String status_approved = jj_rb_Rebate_utils.getRebateLineItemStatus('Approved');
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        String query='SELECT Id,Name,jj_rb_Claim_Date__c,jj_rb_Customer__c,(select id, name,jj_rb_Rebate_Product__r.name,jj_rb_Rebate_Product__c,jj_rb_Quantity__c from Rebate_Claim_Line_Items__r) FROM jj_rb_Rebate_Claim__c where jj_rb_Claim_Date__c = LAST_N_DAYS:1460 AND jj_rb_Status__c =:status_approved AND jj_rb_Claim_Date__c < today AND jj_rb_Customer__c!=null AND RecordTypeId=:homecareclaim_recType order by jj_rb_Claim_Date__c desc';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        List<jj_rb_Rebate_Claim__c> rbcList = (List<jj_rb_Rebate_Claim__c>)scope;  
        System.debug('rebate claims list'+rbcList);
        Set<ID> accIdSet = new Set<ID>();
        Map<ID,List<jj_rb_Rebate_Claim__c>> accRcMap = new Map<ID,List<jj_rb_Rebate_Claim__c>>();
        for(jj_rb_Rebate_Claim__c rc : rbcList){
            String accId = rc.jj_rb_Customer__c;
            if(accRcMap.containsKey(accId)){
                List<jj_rb_Rebate_Claim__c> claims = accRcMap.get(accId);
                if(claims!=null && claims.size()<=2)
                {
                    claims.add(rc);
                }
                accRcMap.put(accId,claims);
            }
            else
            {
                List<jj_rb_Rebate_Claim__c> listclaim= new List<jj_rb_Rebate_Claim__c>{rc};
                accRcMap.put(accId,listclaim);
            }           
        }
        System.debug('accRcMap'+accRcMap);
        List<jj_rb_Rebate_Claim__c> rcList = new List<jj_rb_Rebate_Claim__c>();
        Map<ID,Map<ID,avgcalculation>> m = new Map<ID,Map<ID,avgcalculation>>();
        for(ID accid : accRcMap.keySet()){
            for(jj_rb_Rebate_Claim__c rc:accRcMap.get(accid)){
                rcList.add(rc);
            }
            m.put(accid,calAvgQuantity(rcList));
        }
        System.debug('m@@@'+m);
        List<jj_rb_Tolerance__c> tolList = [select id,jj_rb_Customer__c, jj_rb_Product__c,jj_rb_Product__r.name,
                                                 jj_rb_Price_Tolerance__c, jj_rb_Quantity_Tolerance__c,
                                                 jj_rb_Average_Quantity__c from jj_rb_Tolerance__c 
                                                 where jj_rb_Customer__c=: accRcMap.keySet()];
        System.debug('tolList '+tolList);                                                 
        for(jj_rb_Tolerance__c tol : tolList){
            for(id accid : m.keyset()){
                if(tol.jj_rb_Customer__c == accid){
                    for(id productid : m.get(accid).keyset())
                    {
                        if(tol.jj_rb_Product__c == productid)
                        {
                            tol.jj_rb_Average_Quantity__c = m.get(accid).get(productid).getAvgQty();
                        }   
                    }
                                       
                }                         
            }
        }
        update tolList;   
        System.debug('@@@tolList'+tolList); 
    }
    global void finish(Database.BatchableContext BC){   
       
    }
    public Map<ID,avgcalculation> calAvgQuantity(List<jj_rb_Rebate_Claim__c> listClaims){
        // take the average of quantity 
        Map<id,avgcalculation> mapAvgQtyCal= new Map<id,avgcalculation>();// key:productid
               
        for(jj_rb_Rebate_Claim__c claim:listClaims)
        {
            List<jj_rb_Rebate_Claim_Line_Item__c> claimLineItems = claim.Rebate_Claim_Line_Items__r;
            Decimal quantity=0;
            for(jj_rb_Rebate_Claim_Line_Item__c claimLI : claimLineItems)
            {                
                String productid=claimLI.jj_rb_Rebate_Product__c; 
                // Calculate avgQty               
                if(mapAvgQtyCal.containsKey(productid))
                {
                    avgcalculation avgCal=mapAvgQtyCal.get(productid);
                    avgCal.itemCount += 1;
                    avgCal.quantity+=claimLI.jj_rb_Quantity__c;                
                    mapAvgQtyCal.put(productid,avgCal);
                }
                else
                {
                    avgcalculation avgCal= new avgcalculation();
                    avgCal.itemCount= 1;
                    avgCal.quantity+=claimLI.jj_rb_Quantity__c;                                   
                    mapAvgQtyCal.put(productid,avgCal);
                }
           }    
        }
        return mapAvgQtyCal;
    }
    class avgcalculation
    {
        String productid;
        Integer itemCount=0;
        Decimal quantity=0;
        public Decimal getAvgQty()
        {
           return quantity/itemCount;
        
        }
    }
}