src/objects/jj_rb_Rebate_Contract__c.object
<CustomObject>
    <description>This object stores the contract information created for a customer.</description>
    <fields>
        <fullName>jj_rb_Closure_Comment__c</fullName>
        <label>Closure Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>jj_rb_Closure_Status__c</fullName>
        <label>Closure Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreement value is too low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Contract</label>
    <nameField>
        <displayFormat>RC-{0}</displayFormat>
        <label>Rebate Contract No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/jj_rb_Rebate_Contract_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>jj_rb_Rebate_Contract__c</fullName>
        <label>Rebate Contract</label>
        <referenceTo>jj_rb_Rebate_Contract__c</referenceTo>
        <relationshipLabel>Rebate Contract Line Items</relationshipLabel>
        <relationshipName>Rebate_Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>jj_rb_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Modified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rebate Contract Line Item</label>
    <nameField>
        <displayFormat>RCLI-{0}</displayFormat>
        <label>Rebate Contract Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/jj_rb_Close_contract.cls
public class jj_rb_Close_contract
{
   public jj_rb_rebate_contract__c contract {get; set;} 
   ApexPages.StandardController controller;
    public boolean Block1 {get; set;}
     public boolean Block2 {get; set;}
   public jj_rb_Close_contract(ApexPages.StandardController controller) {
      this.controller = controller;
      contract = (jj_rb_rebate_contract__c)controller.getRecord();  
      contract = [select Id, jj_rb_Closure_Status__c, jj_rb_Closure_Comment__c,jj_rb_status__c,name,(select ID,name,jj_rb_status__c from Rebate_Contract_Line_Items__r )
                        from jj_rb_rebate_contract__c
                        where id = :contract.id limit 1];
       if(contract.jj_rb_Status__c == 'Submitted')
       {
            Block1 = true;
            Block2 = False;
       }
       else
       {
            Block1 = False;
            Block2 = true;
       }
    }

    
   
    public pageReference close_contract()
    { 
        
        String Closed = jj_rb_Rebate_utils.getRebateLineItemStatus('Closed');
        
        list<jj_rb_Rebate_Contract_Line_Item__c> ListLine_Item = new list<jj_rb_Rebate_Contract_Line_Item__c>();
            
        // System.debug('Contract **** '+ contract.Rebate_Contract_Line_Items__r);
        // Iterate over Line Items and update the Status.
        for(jj_rb_Rebate_Contract_Line_Item__c RCIL : contract.Rebate_Contract_Line_Items__r)
        {   Id RecID  = RCIL.RecordTypeId;
            
            if(RecID   == jj_rb_Rebate_utils.getRecordTypeId('Retailer contract line item'))
            { 
                RCIL.jj_rb_status__c = Closed;
                RCIL.RecordTypeId = jj_rb_Rebate_utils.getRecordTypeId('Close Contract Line Item');
            }
            //system.debug('Line Item *** '+ RecID  + ' Custom Setting *** '  + utils.getRecordTypeId('Retailer contract line item'));
            else if(RecID == jj_rb_Rebate_utils.getRecordTypeId('HCP Contract line item'))
            {
                RCIL.jj_rb_status__c = Closed;
                RCIL.RecordTypeId =  jj_rb_Rebate_utils.getRecordTypeId('HCP Close Lineitem');
            }
            ListLine_Item.add(RCIL);
        }
        
        //Update Contract Status
        if(contract.RecordTypeId  == jj_rb_Rebate_utils.getRecordTypeId('Retailer Contract'))
        {
            contract.jj_rb_Status__c = Closed;
            contract.RecordTypeId = jj_rb_Rebate_utils.getRecordTypeId('Close Contract');
        }
        else if(contract.RecordTypeId == jj_rb_Rebate_utils.getRecordTypeId('Home care Provider contract'))
        {
            contract.jj_rb_Status__c = Closed;
            contract.RecordTypeId = jj_rb_Rebate_utils.getRecordTypeId('HCP Close Contract');
        }
        if(!ListLine_Item.isEmpty())
        {
           update(ListLine_Item);
        }
        update(contract);
        pageReference pgref = New ApexPages.StandardController(contract).view();
        pgref.setRedirect(true);
        Return pgref;
    }
}